# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3088b7480e919442ad89a5026fb98d183e38d102a8757ab21339b284855f5d418232e2e29bf85309ed2852af6f7e4e2e7df366ca4f8efc1b2e4fe460f0256425

test:
  secret_key_base: b454f2c1c7ab410faea44b319c96bd4bf493f5b477399f706dde722e5a439775ca0d1a0649c13b5b7016a0faf4e5e64bd344989b6038bfaa0fc92d60c4b828a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
